config/routes.rb
# typed: false
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'lastfm#index'

  get '/lastfm', to: 'lastfm#index'
  get '/about', to: 'about#index'
  post 'start_generation' => 'lastfm#start_button_clicked', as: :start_button_clicked
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# typed: false
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recent_top_album.rb
# typed: strict
class RecentTopAlbum < ApplicationRecord
end

app/controllers/about_controller.rb
# typed: true
# frozen_string_literal: true

# Controller for the About Page
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# typed: strict
class ApplicationController < ActionController::Base
end

app/controllers/lastfm_controller.rb
# typed: true
# frozen_string_literal: true

# Controller for the last fm page
class LastfmController < ApplicationController
  include LastFmModule
  def index
    @albums = []
  end

  def start_button_clicked
    puts 'Getting Albums...'
    @albums = fetch_last_fm_albums('7day')
    puts 'Focking UI updated?'
  end
end

app/helpers/about_helper.rb
# typed: strict
module AboutHelper
end

app/helpers/application_helper.rb
# typed: strict
module ApplicationHelper
end

app/helpers/lastfm_helper.rb
# typed: strict
module LastfmHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<h1>Hello, Rails!</h1>

app/views/lastfm/index.html.erb
<h1>LastFm</h1>

<h2>Albums<h2>
 <label for="timespan">Choose a timespan:</label>

<select name="timespan" id="timespan">
  <option value="7day">Week</option>
  <option value="1month">One Month</option>
  <option value="3month">Three Months</option>
  <option value="6month">Six Months</option>
  <option value="12month">Twelve Months</option>
  <option value="overall">All Time</option>
</select>

<td><%= button_to 'Start', start_button_clicked_path %></td>

<ul>
  <% @albums.each do |album| %>
    <%= image_tag album.cover_small, height: 34, width: 34, alt: 'fun' %>
    <%= album.rank %> <%= album.artist %> - <%= album.title %> <%= album.playcount %> Plays
    <hr>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spoddy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>